Update push.yml
added step check permissions to make sure the right permissions are available in the data directory

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -45,6 +45,9 @@ jobs:
           git config --global user.name 'push repo'
           git config --global user.email 'not@important.com'
 
+      - name: check permissions
+        run: chmod u+w data/ || echo "permissions failed"
+
       - name: commit database
         run: |
           git add -f data/metadata.db
